// List
export const FETCH_LIST_DATA = 'FETCH_LIST_DATA'

// Home
export const FETCH_HOME_TAGS = 'FETCH_HOME_TAGS'
export const FETCH_HOME_CHECKBOX = 'FETCH_HOME_CHECKBOX'
export const FETCH_REGUSER = 'FETCH_REGUSER'
export const FETCH_ADDUSER = 'FETCH_ADDUSER'
export const FETCH_USERLIST = 'FETCH_USERLIST'
